### ISSUE TITLE
State testing issues

### ISSUE THREAD

**Issue by Carifio24** [cosmicds/cosmicds#146]
This issue is for reporting bugs noticed during state testing (for more info, see the wiki page [here](https://github.com/cosmicds/cosmicds/wiki/State-testing-branch)). Please leave a comment here for each issue noticed.

I don't have any sort of guidelines nailed down yet, but a report should at least include:

• The student ID number
• A description of what aspect of the story wasn't properly recreated. Any relevant screenshots would be great.

Known issues:
• The state of the WWT viewer on stage 2 is not recreated (e.g. if you were doing a distance measurement)

**Comment by patudom** [comment]
As student 1780, I got as far as measuring an observed wavelength:
<img width="1206" alt="Screen Shot 2022-09-20 at 9 46 56 AM" src="https://user-images.githubusercontent.com/12750048/191276029-baf4409a-d1c8-4cfc-a7bd-12663b931173.png">

When I returned as the same student, it took me to the right menu location, but there are no widgets.
<img width="1472" alt="Screen Shot 2022-09-20 at 9 50 20 AM" src="https://user-images.githubusercontent.com/12750048/191276180-86643985-a334-4c80-89fe-eeeafab799d5.png">

**Comment by Carifio24** [comment]
@patudom I think I've fixed this problem (and it turns out the console error message _was_ useful this time!)

Basically, our state export/import was accidentally overwriting the widget model ID, which was making it impossible for our widgets to actually be found. I've just pushed a commit that should fix this.

**Comment by Carifio24** [comment]
Currently there's an issue where the selected spectrum is not retained when the student restarts. Working on a fix for that right now.
![no_spectrum](https://user-images.githubusercontent.com/14281631/191850074-f7d47d2b-419f-4c2d-9e48-dbfcb1aaf282.png)

**Comment by patudom** [comment]
Two more issues: 

- the stage state marker isn't in the right place (mee_spe1 on reload; should have been at obs_wav1)
- on reload, app doesn't know that "spectrum tutorial" was already clicked

<img width="1077" alt="Screen Shot 2022-09-23 at 7 57 33 AM" src="https://user-images.githubusercontent.com/12750048/191955459-e48ce71f-9ece-4bd6-99dd-b6c121c11a1d.png">

**Comment by patudom** [comment]
I think something about the student reload fix broke the new student creation.
<img width="1332" alt="Screen Shot 2022-09-23 at 8 11 27 AM" src="https://user-images.githubusercontent.com/12750048/191958135-891ab37a-d078-4ce8-a80e-9a7f69cc63e2.png">

**Comment by patudom** [comment]
I'm not sure if this counts as a "state" issue, but if a student hits a dead tile or failed load (hopefully this will be rare), which happened to me here, when I flagged the galaxy to remove it from my data set, I wasn't able to select a new galaxy to replace it. (This is the version that is deployed for the beta test teacher's preview.)

<img width="1209" alt="Screen Shot 2022-10-14 at 4 55 10 PM" src="https://user-images.githubusercontent.com/12750048/195952406-8b376fbb-2d1a-47d1-bb98-ea6c06e9a053.png">

**Comment by Carifio24** [comment]
I've just submitted a PR in the hubbleds repo that should solve the previous comment.

**Comment by patudom** [comment]
Not sure if this counts as a "state" issue, but it's something we should fix. 

- In Stage 1, if student remeasures a wavelength after already calculating velocities, the velocity does not update. It should either auto-update with a new measurement, or after clicking the runner icon.
- In Stage 2, when the angular size is updated, the behavior is the same as above and needs the same fix as above.

<img width="945" alt="Screen Shot 2022-10-18 at 11 30 04 AM" src="https://user-images.githubusercontent.com/12750048/196477237-5b06ff1d-24f5-449a-a720-b93918f733cf.png">

**Comment by patudom** [comment]
This is not a deal-breaker, so can be ignored until after beta testing.

student_id = 2231. 
- When you log out and log back in, galaxies are not returned to the table in the same order. Some students who have a good visual memory may get confused by this.
- When you log back in, if we highlight the last row the student chose before logging out, we probably also want to display it in the WWT viewer.

How it looked when I logged out:
<img width="1517" alt="Screen Shot 2022-10-18 at 5 19 46 PM" src="https://user-images.githubusercontent.com/12750048/196548089-b86afd4d-89e7-48bf-b2a3-d4057362031e.png">

How it looked when I logged back in:
<img width="1441" alt="Screen Shot 2022-10-18 at 5 22 12 PM" src="https://user-images.githubusercontent.com/12750048/196548153-327a250b-f5f6-4d13-8f47-d76885003c39.png">

**Comment by patudom** [comment]
**CRITICAL**
Student ID: 2231

- I got as far as "Input Wavelengths," but when I logged out and back in, I was sent back to "Reflect on your Data."
- None of my MC responses were stored. I can't tell if my points were correctly saved because voila is timing out right now and I can't see the piggybank in the header in the notebook view.

When I logged out:
<img width="1202" alt="Screen Shot 2022-10-18 at 5 40 35 PM" src="https://user-images.githubusercontent.com/12750048/196550339-f99331a1-c7cf-48c0-93f1-b6d1a959994b.png">

When I logged back in:
<img width="1051" alt="Screen Shot 2022-10-18 at 5 43 05 PM" src="https://user-images.githubusercontent.com/12750048/196550862-d38e0eb8-cf55-4742-a6d9-40f7b8d2a671.png">

**Comment by Carifio24** [comment]
So for student 2231, I can see the MC responses stored in the database. When you say they weren't stored, do you mean that the MCs were auto-populated with your answers?

**Comment by Carifio24** [comment]
Also, just to check: what are the keyword arguments for `Application` in your notebook cell?

**Comment by patudom** [comment]
The mc responses were blank, as if I never did them.

`app = Application(story='hubbles_law', student_id=2231)`
<img width="750" alt="Screen Shot 2022-10-18 at 6 38 52 PM" src="https://user-images.githubusercontent.com/12750048/196558358-06bd10ec-c9f2-404a-97a6-ce9027ce7254.png">

**Comment by patudom** [comment]
- The above screenshot (with no mc displayed) was what I saw in the notebook. 
- In voila, it is displaying my "correct" completed questions, but the progress dots on the slideshow behave as if the questions haven't been completed until you get to a correctly answer question. When you advance to a completed, correctly-answered question, it displays the green feedback, your score, and lets the slideshow advance. (See screenshot)
- I think we probably do want to store the neutral choices and put those back too, if it wouldn't be too much of a pain?

<img width="849" alt="Screen Shot 2022-10-18 at 6 47 51 PM" src="https://user-images.githubusercontent.com/12750048/196559402-113c1619-f819-447e-b4a8-8466ad6769e4.png">

**Comment by patudom** [comment]
I logged out as student 2249 before pressing the running stick figure icon. When I log back in, it's not activated, so I can't progress. I have a feeling the way Harry and I set up the tools to trigger may cause a bunch of these little state issues.

When I logged out:
<img width="1317" alt="Screen Shot 2022-10-20 at 11 07 10 AM" src="https://user-images.githubusercontent.com/12750048/196987717-fb2e91e7-8ecd-4569-a82c-1ca7df3cf94c.png">

When I logged back in:
<img width="1306" alt="Screen Shot 2022-10-20 at 11 08 19 AM" src="https://user-images.githubusercontent.com/12750048/196987764-491e99f4-903a-42dc-9dff-4f51a1d2b34d.png">

**Comment by patudom** [comment]
I'm using the version with PR161 merged in and perhaps should not have had "update_db=True" because I am now having an issue where when I try to use the same Student ID I looked at before (which behaved fine the first time), the graphs are not appearing the 2nd time I've logged in as this user:
<img width="1538" alt="Screen Shot 2022-10-20 at 1 56 06 PM" src="https://user-images.githubusercontent.com/12750048/197023539-3e32b231-222a-4485-8d41-02a439fc1d20.png">

**Comment by patudom** [comment]
Update on the above comment. I navigated back to Stage 1, "logged out" and restarted as this same user and going from Stage 1 to Stage 3, the graph is now being displayed. So there may be some initialization issue when returning to stage 3 without passing from other stages first?

**Comment by Carifio24** [comment]
Yeah, it's an initialization issue. When starting in stage 3, the `_on_stage_index_changed` callback never gets fired, and so the deferred setup never takes place. The easiest change is to only defer the setup if the initial stage index isn't on stage 3. I'll try to think if there's an alternative.

**Comment by patudom** [comment]
If I finish Stage 1, log out, and log back in, if I wanted to update my spectrum measurements, I can't because the toolbar tools show up not-activated on a reload.

Student ID 2259
<img width="931" alt="Screen Shot 2022-10-20 at 4 05 48 PM" src="https://user-images.githubusercontent.com/12750048/197047607-56a01bea-1e63-4d91-a8a6-accb1689afde.png">

The mc answers (including neutral) are filling back in properly now - thank you! The progress dots on the slideshow are still unactivated when you return, so you still have to click through everything instead of being able to jump to a particular slide. (This is not a dealbreaker)
<img width="816" alt="Screen Shot 2022-10-20 at 4 09 03 PM" src="https://user-images.githubusercontent.com/12750048/197048228-8508432c-23d2-4c3f-811f-e22217efa093.png">

**Comment by patudom** [comment]
The "classroom" icon should be activated at this marker. I guess all these tool triggers should be turned on/off based on relative marker indices rather than listening for a coming or going from a particular marker, which is what we do now.

<img width="990" alt="Screen Shot 2022-10-20 at 4 43 13 PM" src="https://user-images.githubusercontent.com/12750048/197054075-8e99bab1-9913-4764-9b33-7c94fca1fcb7.png">

**Comment by patudom** [comment]
**Critical: State Issue 16**
I created a new student, but a mc question I never answered came up as already answered. This happened earlier too, but I didn't want to report it until I was sure it was happening more than once and I wasn't just imagining it. (The prior time it happened it was on the velocity calculation slideshow. This time that particular mc question was not pre-completed, but it happened this time at a later point.)
<img width="1322" alt="Screen Shot 2022-10-20 at 5 36 24 PM" src="https://user-images.githubusercontent.com/12750048/197063576-b803050e-b8c4-456c-b18a-8e1891fff08d.png">

**Comment by patudom** [comment]
**Critical: State Issue 17**
The Stage 3 layer_viewer behaves differently depending on whether a student gets there on a first pass or if we're reading in their stored state data. In particular, the stored data is plotted with an extra fit line that seems to be on top of what gets displayed when going through on a fresh pass.

This is what the layer_viewer looks like when going as a "new" student to stage 3 (and what this is supposed to look like):
<img width="1475" alt="Screen Shot 2022-10-22 at 10 45 00 AM" src="https://user-images.githubusercontent.com/12750048/197345948-d181f39b-f9f0-4bb0-9e05-d75c2419a965.png">


This is what the layer_viewer looks like when reading in data from an existing student in a class. The fit line appears with a label:
<img width="1440" alt="Screen Shot 2022-10-22 at 10 43 55 AM" src="https://user-images.githubusercontent.com/12750048/197345991-6d16b68e-584d-49a0-893e-928ecda7aaba.png">


If you click the "fit lines" button, the line with the label is replaced by the line without the label. (The unlabeled line is what is supposed to appear in this viewer when you turn on the fit lines).
<img width="589" alt="Screen Shot 2022-10-22 at 10 58 13 AM" src="https://user-images.githubusercontent.com/12750048/197346315-73714d2b-8c5d-4303-983b-b72fbe4891d7.png">


If you toggle off the "fit lines" now, it goes away entirely, which is what is supposed to happen. So it seems like the first line that appears (the one with the label) is some extra thing that isn't supposed to be there.
<img width="590" alt="Screen Shot 2022-10-22 at 10 58 19 AM" src="https://user-images.githubusercontent.com/12750048/197346323-5f055ccd-a23b-47b7-b6bf-214d1efba16e.png">

**Comment by patudom** [comment]
**State Issue 18** -if time
This isn't a huge deal breaker, but may be confusing and should be fixed when we have time. As student 2823, I got to the final guideline of Stage 1 but didn't actually click to go to Stage 2. When I logged out and logged back in, it put me back at the beginning of stage 1. (But it had stored all my work, so I didn't have to do it all again - I just needed to know that I was supposed to go straight to Stage 2 at that point.

**Comment by patudom** [comment]
**State Issue 19** - need by Wednesday

Open responses are stored in state, but do not reappear in guideline sho_est1.
<img width="1505" alt="Screen Shot 2022-10-24 at 8 18 33 PM" src="https://user-images.githubusercontent.com/12750048/197654016-23edcb44-6318-43af-bb7d-3ea39f242d2e.png">

**Comment by patudom** [comment]
**State Issue 20** need by Wednesday

MC responses on guideline cards are not being returned
<img width="1362" alt="Screen Shot 2022-10-24 at 9 39 52 PM" src="https://user-images.githubusercontent.com/12750048/197662047-a3871ea9-5af2-442b-ab4e-e06163a5b44f.png">

**Comment by patudom** [comment]
**State Issue 21**

If user logs on on this guideline and returns, no galaxy is selected, so no spectrum appears in the viewer which is confusing:
<img width="1500" alt="Screen Shot 2022-11-07 at 12 27 08 PM" src="https://user-images.githubusercontent.com/12750048/200375662-473bcb7f-1563-4b1c-8162-458bd82514b7.png">

**Comment by patudom** [comment]
**State Issue 23**

As student 3301, I logged out part way through Stage 2, but when I logged back in, I was put back at the beginning of Stage 2.

When I logged out:
<img width="1657" alt="Screen Shot 2022-11-11 at 6 25 59 PM" src="https://user-images.githubusercontent.com/12750048/201444164-f209b7e3-e489-4713-b1da-5b55f9bce521.png">

When I logged back in:
<img width="1729" alt="Screen Shot 2022-11-11 at 6 27 21 PM" src="https://user-images.githubusercontent.com/12750048/201444177-c9e0d9ad-5ad4-4304-9474-0ce5dfe5ff27.png">

**Comment by LilyN11** [comment]
Sorry! I put these in a different issue by mistake 

1) The histogram generated from the seed data seems to very off.  this is the histogram that appeared when I tested the first student. However, this doesn’t make any sense because the seed data was at 18. In the second graph you can see the correct histogram for three students

![pasted image 0](https://user-images.githubusercontent.com/53539773/202525218-905418f3-409c-4b80-ac06-38377fe4fdb4.png)
![pasted image 0-1](https://user-images.githubusercontent.com/53539773/202525308-602ab52b-c171-405d-894c-7c5a2d62c5e9.png)


2) The professional data does not show up for me for either student. This is from the voila version of the app (I don't know how much of this stage is built yet and my other errors are in relation to this stage so let me know if I shouldn't be looking to closely at this stage yet)
![pasted image 0-2](https://user-images.githubusercontent.com/53539773/202525898-6e29dba7-cc51-433c-8c37-d441a587dd61.png)
![pasted image 0-3](https://user-images.githubusercontent.com/53539773/202525921-2becdff1-88a5-43ff-b77a-27a1f58157da.png)
![pasted image 0-4](https://user-images.githubusercontent.com/53539773/202525940-c2430b14-8d72-4fbd-bfdf-19e790077188.png)

**Comment by patudom** [comment]
**State Issue 26**

When the class data reload happens (per https://github.com/cosmicds/hubbleds/pull/103), we need to be sure the line fit is also updated.
<img width="629" alt="Screen Shot 2022-11-30 at 1 45 17 PM" src="https://user-images.githubusercontent.com/12750048/204882530-86c1bc26-2d5a-4ed7-b56b-73b4b69346c1.png">

**Comment by Carifio24** [comment]
@patudom For state issue 26, it's working fine for me using what's on main for both cosmicds and hubbleds. What branches were you using to test this?


https://user-images.githubusercontent.com/14281631/204916567-f4993741-0484-4916-b69d-e6066003937c.mp4

(The other student is being updated off-screen)

**Comment by patudom** [comment]
Interesting. I was using the branches at https://github.com/cosmicds/cosmicds/pull/177 and https://github.com/cosmicds/hubbleds/pull/103.
