### ISSUE TITLE
Spectrum Tool functionality in python

### ISSUE THREAD

**Issue by patudom** [cosmicds/cosmicds#28]
We decided it would be simpler to re-create the Spectrum Tool functionality in python rather than trying to fit the .js  (#19)  code into the ipyvuetify framework of the app. (Also, the .js code is more complex than we need it to be.)

At minimum:
- Viewer should display a line plot of Flux vs. Wavelength. (See #27 for sample data file)
- A moveable vertical line will serve as a wavelength measuring tool that can be clicked to read off the wavelength of a given emission/absorption line (like H-alpha)

If possible:
- Recreate functionality to display the spectrum color image above the graph to show the corresponding wavelength colors with high/low brightness that corresponds to the flux at that wavelength. (@heywooddogwood had a suggestion for how to implement this that I didn't fully understand because I am not familiar with the different schemes for specifying colors in hex RGB, etc. Harry, feel free to add your suggestion here as a comment.)

Alyssa suggested we look at [Plotly Dash](https://plotly.com/dash/) as a way to easily create the plot + wavelength readout functionality, but I am open to other suggestions.

**Comment by heywooddogwood** [comment]
My suggestion was to use HSL values instead of RGB hex, because H represents a linear transition from red to red on the spectrum (representing the Wavelength value), and we can vary L from 0% to 50% (black to full hue saturation) according to flux. The one potential issue I'm not sure of is how accurately the H range maps to the true values of the visible spectrum.
